"""Django settings for idcops project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import hashlib
import os
from pathlib import Path

from dotenv import load_dotenv
from str2bool import str2bool

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载 .env ，默认在 .env 下面
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-)k2j#eh*=q)q@o@8z7-x*h4+9a17#1auo9v97sn*f%623v7$(o"
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("No SECRET_KEY on .env file or environment variable.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str2bool(os.environ.get("DEBUG", "0"))

DEV_ENV = str2bool(os.environ.get("DEV_ENV", "0"))

_ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", ".localhost,127.0.0.1")
ALLOWED_HOSTS = _ALLOWED_HOSTS.split(",")

_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "http://localhost,http://127.0.0.1")
CSRF_TRUSTED_ORIGINS = _ORIGINS.split(",")

INTERNAL_IPS = ["127.0.0.1"]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "mptt",
    "dcrm",
    "django_htmx",
    "django_rq",
    "ninja_jwt",
]

ASGI_APPLICATION = "idcops.asgi.application"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "dcrm.middleware.CoreMiddleware",
]

ENABLE_DEBUG_TOOLBAR = str2bool(os.environ.get("ENABLE_DEBUG_TOOLBAR", "False"))

if ENABLE_DEBUG_TOOLBAR:
    INSTALLED_APPS.append("debug_toolbar")
    MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")


AUTH_USER_MODEL = "dcrm.User"

ROOT_URLCONF = "idcops.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "dcrm.context_processors.menus",
                "dcrm.context_processors.site_meta",
            ],
        },
    },
]

WSGI_APPLICATION = "idcops.wsgi.application"


# Database
# https://docs.djangoproject.com/zh-hans/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB", "dcrm"),
        "USER": os.environ.get("POSTGRES_USER", "postgres"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "postgres"),
        "HOST": os.environ.get("POSTGRES_HOST", "postgres"),
        "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "pool": True,  # 连接池
            "client_encoding": "utf8",
        },
    }
}

# Cache
# https://docs.djangoproject.com/zh-hans/5.2/ref/settings/#caches
# https://docs.djangoproject.com/zh-hans/5.2/topics/cache/#redis

REDIS_HOST = os.environ.get("REDIS_HOST", "localhost")
REDIS_PORT = os.environ.get("REDIS_PORT", "6379")
REDIS_DB = os.environ.get("REDIS_DB", "0")
REDIS_USER = os.environ.get("REDIS_USER", "")
REDIS_PASS = os.environ.get("REDIS_PASS", "")
REDIS_SERVER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

if REDIS_USER or REDIS_PASS:
    REDIS_SERVER_URL = (
        f"redis://{REDIS_USER}:{REDIS_PASS}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
    )

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_SERVER_URL,
    }
}

# https://docs.djangoproject.com/zh-hans/5.2/ref/settings/#session-engine

SESSION_ENGINE_TYPE = os.environ.get("SESSION_ENGINE_TYPE", "db")
SESSION_ENGINE = f"django.contrib.sessions.backends.{SESSION_ENGINE_TYPE}"

SESSION_COOKIE_SECURE = str2bool(os.environ.get("SESSION_COOKIE_SECURE", "0"))
CSRF_COOKIE_SECURE = str2bool(os.environ.get("CSRF_COOKIE_SECURE", "0"))

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = os.environ.get("TIME_ZONE", "Asia/Shanghai")

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

SITE_PREFIX = os.environ.get("SITE_PREFIX", "/")

if SITE_PREFIX:
    SITE_PREFIX = SITE_PREFIX.rstrip("/") + "/"

STATIC_URL = f"{SITE_PREFIX}static/"

STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = f"{SITE_PREFIX}media/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 配置上传文件的最大字段数，默认值是 1000
# https://docs.djangoproject.com/zh-hans/4.2/ref/settings/#data-upload-max-number-fields

DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# ADMINS 指定特定管理员，只有指定的用户才可以动态修改系统设置
# 必须包含 (用户名，用户邮箱)
ADMINS = [("admin", "dcrm@example.com")]

# 日志配置
# 日志文件保存路径
LOG_DIR = os.path.join(BASE_DIR, "logs")
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOG_MAX_BYTES = int(os.environ.get("LOG_MAX_BYTES", 10 * 1024 * 1024))  # 默认10MB
LOG_BACKUP_COUNT = int(os.environ.get("LOG_BACKUP_COUNT", 10))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        # 详细格式 - 用于文件日志
        "verbose": {
            "format": "[%(asctime)s] %(levelname)-8s [%(name)s:%(lineno)d] [%(process)d:%(thread)d] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        # 控制台格式 - 简洁清晰
        "console": {
            "format": "%(levelname)-8s [%(name)s] %(message)s",
        },
        # 标准格式 - 平衡详细程度
        "standard": {
            "format": "[%(asctime)s] %(levelname)-8s [%(name)s:%(lineno)d] %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        # JSON格式 - 用于日志分析系统
        "json": {
            "format": '{"timestamp":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s","line":%(lineno)d,"process":%(process)d,"thread":%(thread)d,"message":"%(message)s"}',
            "datefmt": "%Y-%m-%dT%H:%M:%S",
        },
        # RQ任务队列专用格式
        "rq_console": {
            "format": "[%(asctime)s] %(levelname)-8s [RQ-%(name)s] %(message)s",
            "datefmt": "%H:%M:%S",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "handlers": {
        # 控制台处理器 - 只输出INFO及以上级别
        "console": {
            "level": "INFO",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
            "formatter": "console",
        },
        # 开发环境控制台 - 仅在DEBUG模式下启用INFO级别
        "console_dev": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "console",
            "filters": ["require_debug_true"],
        },
        # RQ任务队列控制台
        "rq_console": {
            "level": "INFO",
            "class": "rq.logutils.ColorizingStreamHandler",
            "formatter": "rq_console",
        },
        # 应用程序日志文件 - INFO及以上
        "file_app": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "app.log"),
            "maxBytes": LOG_MAX_BYTES,
            "backupCount": LOG_BACKUP_COUNT,
            "formatter": "standard",
            "encoding": "utf-8",
        },
        # 错误日志文件 - ERROR及以上
        "file_error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "error.log"),
            "maxBytes": LOG_MAX_BYTES,
            "backupCount": LOG_BACKUP_COUNT,
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        # 调试日志文件 - 仅在DEBUG模式下启用
        "file_debug": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "debug.log"),
            "maxBytes": LOG_MAX_BYTES,
            "backupCount": LOG_BACKUP_COUNT,
            "formatter": "verbose",
            "filters": ["require_debug_true"],
            "encoding": "utf-8",
        },
        # 安全相关日志
        "file_security": {
            "level": "WARNING",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "security.log"),
            "maxBytes": LOG_MAX_BYTES,
            "backupCount": LOG_BACKUP_COUNT,
            "formatter": "verbose",
            "encoding": "utf-8",
        },
        # 数据库查询日志 - 仅在DEBUG模式下启用
        "file_db": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "db.log"),
            "maxBytes": LOG_MAX_BYTES,
            "backupCount": LOG_BACKUP_COUNT,
            "formatter": "standard",
            "filters": ["require_debug_true"],
            "encoding": "utf-8",
        },
    },
    "loggers": {
        # Django核心日志
        "django": {
            "handlers": ["console", "file_app"],
            "level": "INFO",
            "propagate": False,
        },
        # Django请求处理日志
        "django.request": {
            "handlers": ["console", "file_error", "file_security"],
            "level": "WARNING",
            "propagate": False,
        },
        # Django安全相关日志
        "django.security": {
            "handlers": ["console", "file_security"],
            "level": "WARNING",
            "propagate": False,
        },
        # 数据库查询日志 - 仅在DEBUG模式下记录
        "django.db.backends": {
            "handlers": ["file_db"],
            "level": "DEBUG",
            "propagate": False,
        },
        # RQ任务队列日志
        "rq.worker": {
            "handlers": ["rq_console", "file_app"],
            "level": "INFO",
            "propagate": False,
        },
        # 应用程序日志
        "dcrm": {
            "handlers": ["console_dev", "file_app", "file_error"],
            "level": "INFO",
            "propagate": False,
        },
        # 机器学习模块日志
        "dcrm.apar": {
            "handlers": ["console_dev", "file_app"],
            "level": "INFO",
            "propagate": False,
        },
        # 服务模块日志
        "dcrm.services": {
            "handlers": ["console_dev", "file_app", "file_error"],
            "level": "INFO",
            "propagate": False,
        },
        # 任务模块日志
        "dcrm.tasks": {
            "handlers": ["console_dev", "file_app"],
            "level": "INFO",
            "propagate": False,
        },
        # 监控模块日志
        "dcrm.monitoring": {
            "handlers": ["console_dev", "file_app"],
            "level": "INFO",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console", "file_app", "file_error"]
        + (["file_debug"] if DEBUG else []),
        "level": "INFO",
    },
}


# 二维码公开展示字段配置
# 扫码后公开页面展示的字段（无需登录即可查看），可在此处增减字段
QR_PUBLIC_FIELDS = {
    "dcrm.rack": [
        "room",
        "name",
        "rack_type",
        "status",
        "space_usage",
        "tenant",
        "opening_date",
        "contract_power",
        "u_height",
        "pdu_count",
        "pdu_16a_count",
        "description",
    ],
    "dcrm.device": ["name", "model", "type", "rack", "position", "status"],
    "dcrm.onlinedevice": ["name", "model", "type", "rack", "position", "status"],
}

# 配置搜索和过滤时要排除的字段
SEARCH_FILTER_EXCLUDE_FIELDS = [
    "id",
    "created_at",
    "updated_at",
    "deleted_at",
    "created_by",
    "updated_by",
    "password",
    "is_actived",
    "is_staff",
    "is_superuser",
    "last_login",
    "date_joined",
]

# 创建基础 RQ 配置
RQ_BASE_CONFIG = {
    "URL": REDIS_SERVER_URL,
    "DEFAULT_TIMEOUT": 500,
    "WORKER_PID_PATH": "/tmp",
}

# 为所有队列使用相同的基础配置
RQ_QUEUES = {
    "default": RQ_BASE_CONFIG,
    "high": RQ_BASE_CONFIG,
    "low": RQ_BASE_CONFIG,
}

# ML 模型 ROOT PATH
ML_ROOT = os.path.join(MEDIA_ROOT, "ml")

# 预加载设备型号预测模型
PRELOAD_DEVICE_ML_MODEL = str2bool(os.environ.get("PRELOAD_DEVICE_ML_MODEL", "0"))

# 预加载设备型号预测模型路径
DEVICE_ML_MODEL_PATH = os.path.join(ML_ROOT, "device_model_predictor.joblib")

# 文档分类器模型路径（默认 MEDIA_ROOT/ml/document_classifier.pickle）
DOC_CLASSIFIER_MODEL_PATH = os.environ.get(
    "DOC_CLASSIFIER_MODEL_PATH",
    os.path.join(ML_ROOT, "document_classifier.pickle"),
)

# 是否启用自动填充
AUTO_FILL_ENABLED = True

# 自动填充的模型
AUTO_FILL_MODELS = [
    "dcrm.device",
    "dcrm.devicehost",
    "dcrm.deviceport",
    "dcrm.patchcord",
    "dcrm.Warehouse",
    "dcrm.InventoryItem",
    "dcrm.ItemInstance",
]


# OCR 代理配置
OCR_AGENT = os.environ.get("OCR_AGENT", "baidu_ocr")
BDOCR_APPID = os.environ.get("BDOCR_APPID")
BDOCR_API_KEY = os.environ.get("BDOCR_API_KEY")
BDOCR_SECERT_KEY = os.environ.get("BDOCR_SECERT_KEY")

# InfluxDB 配置
INFLUXDB_URI = os.environ.get("INFLUXDB_URI", "http://127.0.0.1:8086")
INFLUXDB_ORG = os.environ.get("INFLUXDB_ORG", "dcrm")
INFLUXDB_TOKEN = os.environ.get("INFLUXDB_TOKEN", "")

# 通知配置

# 自动修复缓存计数时间间隔
AUTOFIX_CACHE_COUNT_INTERVAL = int(
    os.environ.get("AUTOFIX_CACHE_COUNT_INTERVAL", 60 * 60 * 0.5)
)  # 默认30分钟

# 训练设备模型时间间隔
TRAIN_DEVICE_MODEL_INTERVAL = int(
    os.environ.get("TRAIN_DEVICE_MODEL_INTERVAL", 60 * 60 * 12)
)  # 默认12小时

# 训练文档分类器时间间隔
TRAIN_DOCUMENT_CLASSIFIER_INTERVAL = int(
    os.environ.get("TRAIN_DOCUMENT_CLASSIFIER_INTERVAL", 60 * 60 * 12)
)  # 默认12小时

# ============================================================================
# Census 使用情况统计配置
# ============================================================================
# 匿名使用情况统计，帮助开发者了解部署数量和版本分布
# 仅上报：软件版本、Python版本、匿名部署ID（不包含任何用户数据）
# 用户可通过设置 CENSUS_REPORTING_ENABLED=0 关闭此功能

# 是否启用匿名使用情况上报（默认开启）
CENSUS_REPORTING_ENABLED = str2bool(os.environ.get("CENSUS_REPORTING_ENABLED", "1"))

# 离线部署模式（跳过所有外部网络请求）
ISOLATED_DEPLOYMENT = str2bool(os.environ.get("ISOLATED_DEPLOYMENT", "0"))

# 基于 SECRET_KEY 生成的匿名部署ID（16位哈希）
DEPLOYMENT_ID = hashlib.sha256(SECRET_KEY.encode("utf-8")).hexdigest()[:16]


# 软件版本号（从 pyproject.toml 读取，无需安装包）
def _get_version():
    """从 pyproject.toml 读取版本号"""
    import re

    try:
        pyproject_path = BASE_DIR / "pyproject.toml"
        content = pyproject_path.read_text(encoding="utf-8")
        match = re.search(r'^version\s*=\s*["\']([^"\']+)["\']', content, re.MULTILINE)
        if match:
            return match.group(1)
    except Exception:
        pass
    return "0.0.0-dev"


VERSION = _get_version()
